///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest14
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTest14Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("4defd455-ef94-4c2b-8496-577afff74cc0")]
    public partial class MyTest14Repository : RepoGenBaseFolder
    {
        static MyTest14Repository instance = new MyTest14Repository();
        MyTest14RepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the MyTest14Repository element repository.
        /// </summary>
        [RepositoryFolder("4defd455-ef94-4c2b-8496-577afff74cc0")]
        public static MyTest14Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTest14Repository() 
            : base("MyTest14Repository", "/", null, 0, false, "4defd455-ef94-4c2b-8496-577afff74cc0", ".\\RepositoryImages\\MyTest14Repository4defd455.rximgres")
        {
            _applicationundertest = new MyTest14RepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("4defd455-ef94-4c2b-8496-577afff74cc0")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("2597e888-0881-4f81-aa35-a27714beed59")]
        public virtual MyTest14RepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTest14RepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("2597e888-0881-4f81-aa35-a27714beed59")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _functionaluitestautomationwithintelInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, false, "2597e888-0881-4f81-aa35-a27714beed59", "")
            {
                _functionaluitestautomationwithintelInfo = new RepoItemInfo(this, "FunctionalUITestAutomationWithIntel", ".//div[#'main-content']/article/div/div/div/div[1]/div/div[1]/div[1]/?/?/h1[@innertext>'Functional UI Test Automation']", ".//div[#'main-content']//h1[@innertext>'Functional UI Test Automation']", 30000, null, "fa6ae4fc-5a88-4767-bd60-c73d93f0bd28");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2597e888-0881-4f81-aa35-a27714beed59")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2597e888-0881-4f81-aa35-a27714beed59")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FunctionalUITestAutomationWithIntel item.
            /// </summary>
            [RepositoryItem("fa6ae4fc-5a88-4767-bd60-c73d93f0bd28")]
            public virtual Ranorex.H1Tag FunctionalUITestAutomationWithIntel
            {
                get
                {
                    return _functionaluitestautomationwithintelInfo.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The FunctionalUITestAutomationWithIntel item info.
            /// </summary>
            [RepositoryItemInfo("fa6ae4fc-5a88-4767-bd60-c73d93f0bd28")]
            public virtual RepoItemInfo FunctionalUITestAutomationWithIntelInfo
            {
                get
                {
                    return _functionaluitestautomationwithintelInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
